### ISSUE TITLE
Create ViewModels for the Blazor components

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/ResourceManagement#56]
To support future unit testing, we should start using ViewModels with the Blazor Components.

**Comment by SimonGeering** [comment]
@csharpfritz please assign this one to me. 
Will it be ok to pull view models out into .net Standard DLL so it can be referenced from both the unit-test project and the Client project?

**Comment by SimonGeering** [comment]
OK, it looks like the unit test project already has a reference to the web app, so I guess that works for the solution. I'll put the ViewModels in the web app for now then and there will be the option to pull them out into another DLL later, not least because naming things is hard and it's probably best for you to name it.

**Comment by csharpfritz** [comment]
That works for me.  Thanks!



Jeff
